services:
  redis:
    ports:
      - "${REDIS_PORT:-6379}:6379"
  rabbitmq:
    ports:
      - "${RABBITMQ_PORT:-5672}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT:-15672}:15672"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-admin}
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
  django:
    ports:
      - "${DJANGO_WEB_PORT:-8000}:8000"
    volumes:
      - .:/home/django/
  celery:
    volumes:
      - .:/home/django/
  celery-beat:
    volumes:
      - .:/home/django/
