apiVersion: apps/v1
kind: Deployment
metadata:
  name: dj-ms-core
  labels:
    app: dj-ms-core
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dj-ms-core
  template:
    metadata:
      labels:
        app: dj-ms-core
    spec:
      containers:
        - image: harleyking/dj-ms-core:latest
          name: dj-ms-core
          envFrom:
            - secretRef:
                name: dj-ms-core-secret
          ports:
            - containerPort: 8000
              name: gunicorn
