apiVersion: v1
kind: Service
metadata:
  name: dj-ms-core
  labels:
    app: dj-ms-core
spec:
  type: NodePort
  selector:
    app: dj-ms-core
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30000
